# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28f1c81198e5e77dbb45e4bafed1cf1790b4dc94f963821c0f7ff2de295227b4d7f3cb8bc92e8064d4a9dc164dcd764756e68f038dbecfa3f5df7da1719a42ad

test:
  secret_key_base: f6260cbb62b8830840360e67cd08184d7a9976008c589e5f5db203e30a2a9e6407f49ea9a70004949c8b932f84ec3d3e2551e35403dafeee6fb676836f04204f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
